### ISSUE TITLE
`denote-explore-stats` is missing

### ISSUE THREAD

**Issue by j4kub5** [pprevos/denote-explore#1]
`denote-explore-stats.el` file is missing causing: 

`Error: Cannot open load file: No such file or directory, denote-explore-stats`

_PS The idea for the package is great!_

**Comment by pprevos** [comment]
Hi, I have just committed a new version. The package is no way near complete. Ill work on it later this year. Commit: 07be570

**Comment by pprevos** [comment]
FYI, the latest version of the network visualisation has improved a bit as the script now takes parameters, so it uses the `denote-directory` variable and you can configure the output filename.
