### ISSUE TITLE
Alternative Implementation Using Python

### ISSUE THREAD

**Issue by jgarte** [pprevos/denote-explore#13]
Hi,

Great package!

Would you accept an alternative implementation of the [R](https://github.com/pprevos/denote-explore/blob/main/denote-explore-network.R) code in Python?

**Comment by pprevos** [comment]
Hi, happy to accept a Python alternative. We can keep both options, for R and Python users. and make it an option to select. 

Not sure if Pandas is the go, you best use iGraph to create the network object. There is also the D3Graph python library to implement D3JS.

**Comment by pprevos** [comment]
From commit [c4d10b9](https://github.com/pprevos/denote-explore/commit/c4d10b9b7f0782d2f245232a78f2cae7f7eae509), Denote now uses a D3.js template to generate graphs. 

There is no more need for external software such as R or Python.
