### ISSUE TITLE
`denote-explore-identify-duplicate-notes` could instead use `find-dired`

### ISSUE THREAD

**Issue by swflint** [pprevos/denote-explore#19]
I think it might be interesting to extend the UI for `denote-explore-identify-duplicate-notes` to use `find-dired`, which provides a number of features that *could* make it easier to fix issues with duplicate IDs (e.g., using `wdired` or `dired+` related filtering features).

I'll PR in a bit.

**Comment by pprevos** [comment]
I like your thinking. I had planned to look into something similar.
