### ISSUE TITLE
Double Quotes in titles are not escaped in generated graphviz files

### ISSUE THREAD

**Issue by swflint** [pprevos/denote-explore#24]
This causes graphviz to error, and prevents generation of the graph.

**Comment by pprevos** [comment]
Hi Samuel,

I am looking into this issue. I am struggling getting Emacs to properly escape the quotation marks in a title.

In the variable it is properly encoded as `"This is a \"test\" title"`, but when it is written to disk the escapes vanish.

P:)

**Comment by swflint** [comment]
It would probably need to be something like `"This is a \\\"test\\\" title"`, I think.
