### ISSUE TITLE
Possible to make release versions tractable (correspondence commit-version or other)

### ISSUE THREAD

**Issue by hapst3r** [pprevos/denote-explore#26]
Hej Peter,

I am preparing to add DENOTE-EXPLORE to Guix. I am having some troubles because I can't really find a correspondence between the versions you mention in the README and the commits in the repository.

Other packages in Guix use either commits or release tags, but on this repo I couldn't find a release tag and I was unable to discern one commit that corresponds to a particular version as mentioned in the README.

Is is possible that you implement either of the two -- release tags or mentioning a tag corresponding to a version -- so that I can add DENOTE-EXPLORE to Guix?

Have a nice day,
Olivier

**Comment by pprevos** [comment]
Hi Oliver,

I am honored to be considered to be part of Guix.

You need to help me a bit. I am not a software developer so I am not sure exactly what you are after. The version numbers I refer to are mentioned in the source code.

Should I add releases to the GitHub page to satisfy your requirement? Do I do this for every commit?

P:)

**Comment by hapst3r** [comment]
Hi Peter,

adding a release to the GitHub page might be the easiest way. It would be convenient if you could add a release whenever you have a Version bump (e.g. one release for 3.0 and another for 3.1 etc).

The alternative I suggested would entail mentioning one particular commit per version (e.g. a7bf53m - Version 3.1, r12wq84k - Version 3.0), so that I could refer to the Version using this commit (find below an example package recipe using a commit, dunno if that helps).

I removed the package recipe code, as mail replies don't support mark down and thus the well-structured recipe appears just as a garbled mess. Find the same (exemplary) guix package recipe here: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/emacs-xyz.scm#n13244

Have a nice day, and merry Christmas to you :-)

Am 23. Dezember 2024 21:14:50 MEZ schrieb Peter Prevos ***@***.***>:

**Comment by pprevos** [comment]
Thanks, I'll get it done after the holidays.

Merry Christmas 🎄

**Comment by pprevos** [comment]
Hi Oliver,

I have made some updates to the code and manual and added a release (Version 3.2, first official release).

I will update these as new functionality is added.

P:)

**Comment by hapst3r** [comment]
Hi Peter,

thank you very much for making a release. In the meantime, I learned that it doesn't matter if you make a release proper or if you tag a release - both can easily be referred to in the Guix code (I'm also new to this stuff to be honest).

I will prepare the inclusion of the package into the Guix codebase (it is peer-reviewed) and will try to remember to notify you once it is included.

Have a good time, thanks for your effort <3

Am 29. Dezember 2024 02:01:40 MEZ schrieb Peter Prevos ***@***.***>:

**Comment by pprevos** [comment]
Is it like MELPA?

The pick releases from Github as stable but also use the latest commit in their recipes.

**Comment by hapst3r** [comment]
Sorry, took me some time to get back to it. I'm not at all familiar with MELPA but will try to answer anyways.

While in theory both Github releases and commits can be used, IMO a release is preferable since every new commit amounts to a change that needs to be committed (to the Guix codebase) and peer-reviewed semi-manually -- a lot of stuff can be done automatically, but there is a bit of manual work involved on at least two sides (committer, peer-reviewer).

In case of DENOTE-EXPLORE, my "problem" was that while I saw versions AND commits, I was unable to discern a relationship between the two which I wanted to preserve when adding the package to a distro codebase :)

Anyway, I'm preparing the Guix package right now and it is likely to be added within the upcoming days I suppose. When it is part of the codebase, it can be browsed here: https://packages.guix.gnu.org/

Thanks for your time, have a good day :)

**Comment by pprevos** [comment]
I will keep the major versions on GitHub updated.

Heard a lot of good things about Guix, perhaps I should give it a whirl.

**Comment by hapst3r** [comment]
Thank you so much, I will try to keep it updated :-)

Guix is awesome, but it also takes quite some getting used to. I'd suggest trying out the package manager first, which is already pretty awesome for what it can do. I was so eager, years ago, to install it as system distribution when my knowledge of Linux as a system and my programming too was clearly not up to it, that I wouldn't recommend it as a first step (Guix can be both, only a package manager or a fully fledged system distribution).

In case you are interested, some friendly resources I found:
- https://www.futurile.net/resources/guix/ (good intro I would say)
- https://guix.gnu.org/de/blog/tags/dissecting-guix/ (goes a lot deeper into "the meat")
- https://guix.gnu.org/manual/devel/en/ (the manual, rather technical, sometimes lighter on examples than you'd want, but very thorough in my understanding)
- https://guix.gnu.org/cookbook/en/html_node/ (the cookbook, with nice practical tutorials for once you want to get your hands dirty)

Have a good day :)

Am 11. Januar 2025 21:48:21 MEZ schrieb Peter Prevos ***@***.***>:
