### ISSUE TITLE
dashboard and all-the-icons as dependency

### ISSUE THREAD

**Issue by Jousimies** [pprevos/denote-explore#3]
It's better not make dashboard and all-the-icons as dependency, someone may not use them.

or 
```
(require 'dashboard nil t)

(require 'all-the-icons nil t)
```

**Comment by pprevos** [comment]
Hi,

Makes sense. I'll fix it in the next version, which is in progress.

Regards

P:)

**Comment by pprevos** [comment]
By the way, do you know how to make the dashboard widget clickable so that they activate a function when clicked?

**Comment by pprevos** [comment]
Hi, Just committed the latest version [dccb677](https://github.com/pprevos/denote-explore/commit/dccb6772f5e41b02597ab25134f81b7b0eb51c64), which includes your suggestions. I also separated the dashboard widget to another file as to not enforce the dependencies.
